spring: 
 profiles: 
  active: 
  - dev

---

spring: 
 profiles: dev #开发环境
 application: 
 name: microservicecloud-config-lqjq-dev

---

spring: 
 profiles: test #测试环境
 application: 
  name: microservicecloud-config-lqjq-test

# 保存为UTF-8格式