spring:
 profiles: 
  active: 
   - dev

---

server: 
 port: 1111


spring: 
 profiles: dev
lqjq: 
 name: client-dev
 
---

spring: 
 profiles: test


server: 
 port: 2222

lqjq: 
 name: client-test
